// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiGpRgOxgguTSTB2wBox5qLsnpea_KU2g',
    appId: '1:861290917334:web:959dd23f9d4a0f6c0d8877',
    messagingSenderId: '861290917334',
    projectId: 'serviceconnect-kavya-2026',
    authDomain: 'serviceconnect-kavya-2026.firebaseapp.com',
    storageBucket: 'serviceconnect-kavya-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQqfR1pDUFesFpEIppTLmYPTI5DPTa-4',
    appId: '1:861290917334:android:8d844a32206923b80d8877',
    messagingSenderId: '861290917334',
    projectId: 'serviceconnect-kavya-2026',
    storageBucket: 'serviceconnect-kavya-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTbKjP129bcS660bA81ri98lR42dPLGl8',
    appId: '1:861290917334:ios:beb0691a4f0afe600d8877',
    messagingSenderId: '861290917334',
    projectId: 'serviceconnect-kavya-2026',
    storageBucket: 'serviceconnect-kavya-2026.firebasestorage.app',
    iosBundleId: 'com.example.serviceConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTbKjP129bcS660bA81ri98lR42dPLGl8',
    appId: '1:861290917334:ios:beb0691a4f0afe600d8877',
    messagingSenderId: '861290917334',
    projectId: 'serviceconnect-kavya-2026',
    storageBucket: 'serviceconnect-kavya-2026.firebasestorage.app',
    iosBundleId: 'com.example.serviceConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiGpRgOxgguTSTB2wBox5qLsnpea_KU2g',
    appId: '1:861290917334:web:16a42151bd80d4bf0d8877',
    messagingSenderId: '861290917334',
    projectId: 'serviceconnect-kavya-2026',
    authDomain: 'serviceconnect-kavya-2026.firebaseapp.com',
    storageBucket: 'serviceconnect-kavya-2026.firebasestorage.app',
  );
}
